- alias: Luftbefeuchter Arbeitszimmer off
  id: Luftbefeuchter Arbeitszimmer off
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_arbeitszimmer_humidity
      above: input_number.humidity_control_humidifier_stop
      for: "00:05:00" # Humidity must be below the threshold for 5 minutes
  action:
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_arbeitszimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 2.OG
        message: "Luftbefeuchter 2.OG aus"
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_arbeitszimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 2.OG
        message: "Luftbefeuchter 2.OG aus"
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
