# Automatisierung für Luftbefeuchter EG
- alias: Luftbefeuchter Wohnzimmer on
  id: Luftbefeuchter Wohnzimmer on
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_kueche_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:05:00"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.luftbefeuchter_wohnzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter EG
        message: "Luftbefeuchter EG an"
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - if:
        - condition: state
          entity_id: input_boolean.humidity_control_notify_details
          state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier EG started"
            title: "Humidifier EG started"
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.temperatursensor_kueche_humidity
          above: input_number.humidity_control_humidifier_stop
          for: "00:02:00"
      timeout: "02:00:00"
      continue_on_timeout: true
    - if:
        - condition: template
          value_template: "{{ wait.trigger == none }}"
      then:
        - service: logbook.log
          data:
            name: Luftbefeuchter EG
            message: "Luftbefeuchter EG - Timeout reached! Humidity did not reach the stop threshold."
            entity_id: humidifier.deerma_jsq2w_a365_humidifier
        - if:
            - condition: state
              entity_id: input_boolean.humidity_control_notify_details
              state: "on"
          then:
            - service: notify.mobile_app_pixel_9_pro
              data:
                message: "Humidifier EG - Timeout reached! Humidity did not reach the stop threshold."
                title: "Humidifier EG - Timeout"
                entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.luftbefeuchter_wohnzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter EG
        message: "Luftbefeuchter EG aus"
    - if:
        - condition: state
          entity_id: input_boolean.humidity_control_notify_details
          state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier EG off"
            title: "Humidifier EG off"
