- alias: Luftbefeuchter Wohnzimmer off
  id: Luftbefeuchter Wohnzimmer off
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_kueche_humidity
      above: input_number.humidity_control_humidifier_stop
      for: "00:05:00" # Humidity must be below the threshold for 5 minutes
  action:
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_wohnzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter EG
        message: "Luftbefeuchter EG"
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_wohnzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter EG
        message: "Luftbefeuchter EG aus"
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
