# Automatisierung für Luftbefeuchter 2.OG
- alias: Luftbefeuchter Arbeitszimmer on
  id: Luftbefeuchter Arbeitszimmer on
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_arbeitszimmer_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:05:00"
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.luftbefeuchter_arbeitszimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 2.OG
        message: "Luftbefeuchter 2.OG an"
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - if:
        - condition: state
          entity_id: input_boolean.humidity_control_notify_details
          state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier 2.OG started"
            title: "Humidifier 2.OG started"
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.temperatursensor_arbeitszimmer_humidity
          above: input_number.humidity_control_humidifier_stop
          for: "00:02:00"
      timeout: "02:00:00"
      continue_on_timeout: true
    - if:
        - condition: template
          value_template: "{{ wait.trigger == none }}"
      then:
        - service: logbook.log
          data:
            name: Luftbefeuchter 2.OG
            message: "Luftbefeuchter 2.OG - Timeout reached! Humidity did not reach the stop threshold."
            entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
        - if:
            - condition: state
              entity_id: input_boolean.humidity_control_notify_details
              state: "on"
          then:
            - service: notify.mobile_app_pixel_9_pro
              data:
                message: "Humidifier 2.OG - Timeout reached! Humidity did not reach the stop threshold."
                title: "Humidifier 2.OG - Timeout"
                entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - service: input_boolean.turn_off
      target:
        entity_id: input_boolean.luftbefeuchter_arbeitszimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 2.OG
        message: "Luftbefeuchter 2.OG aus"
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - if:
        - condition: state
          entity_id: input_boolean.humidity_control_notify_details
          state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier 2.OG off"
            title: "Humidifier 2.OG off"
