#Automatisierung für Luftbefeuchter 1.OG
- alias: Luftbefeuchter Kinder on
  id: Luftbefeuchter Kinder on
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_lego_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: humidifier.deerma_jsq2w_7134_humidifier
      state: "off" # Only trigger if the humidifier is currently off
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.luftbefeuchter_kinderspielzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 1OG
        message: "Luftbefeuchter 1OG an"
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
