- alias: Luftbefeuchter Kinder off
  id: Luftbefeuchter Kinder off
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_lego_humidity
      above: input_number.humidity_control_humidifier_stop
      for: "00:01:00"
  condition:
    condition: state
    entity_id: humidifier.deerma_jsq2w_7134_humidifier
    state: "on"
  action:
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_kinderspielzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 1.OG
        message: "Luftbefeuchter 1.OG aus"
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
