#Automatisierung für Luftbefeuchter 1.OG
- alias: Luftbefeuchter Kinder on
  id: Luftbefeuchter Kinder on
  trigger:
    - platform: numeric_state
      entity_id: sensor.temperatursensor_lego_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:05:00" # Humidity must be below the threshold for 5 minutes
  action:
    - service: input_boolean.turn_on # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_kinderspielzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 1.OG
        message: "Luftbefeuchter 1.OG an"
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - if:
        condition: state
        entity_id: input_boolean.humidity_control_notify_details # Your input_boolean
        state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier 1.OG started"
            title: "Humidifier 1.OG started"
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - wait_for_trigger:
        - platform: numeric_state
          entity_id: sensor.temperatursensor_lego_humidity
          above: input_number.humidity_control_humidifier_stop
          for: "00:02:00" # Humidity must be below the threshold for 2 minutes
      timeout: "02:00:00" # Add a timeout (2 hours in this case)
      continue_on_timeout: true # Continue even if timeout is reached
    - if: # Check if the wait_for_trigger timed out
        - condition: template
          value_template: "{{ wait.trigger == none }}" # Special condition for timeout
      then:
        - service: logbook.log
          data:
            name: Luftbefeuchter 1.OG
            message: "Luftbefeuchter 1.OG - Timeout reached! Humidity did not reach the stop threshold."
            entity_id: humidifier.deerma_jsq2w_7134_humidifier
        - if:
            - condition: state
              entity_id: input_boolean.humidity_control_notify_details
              state: "on"
          then:
            - service: notify.mobile_app_pixel_9_pro
              data:
                message: "Humidifier 1.OG - Timeout reached! Humidity did not reach the stop threshold."
                entity_id: humidifier.deerma_jsq2w_7134_humidifier
                title: "Humidifier 1.OG - Timeout"
    - service: humidifier.turn_off
      target:
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - service: input_boolean.turn_off # Automatisierung startet
      target:
        entity_id: input_boolean.luftbefeuchter_kinderspielzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 1.OG
        message: "Luftbefeuchter 1.OG aus"
        entity_id: humidifier.deerma_jsq2w_7134_humidifier
    - if:
        condition: state
        entity_id: input_boolean.humidity_control_notify_details # Your input_boolean
        state: "on"
      then:
        - service: notify.mobile_app_pixel_9_pro
          data:
            message: "Humidifier 1.OG off"
            title: "Humidifier 1.OG off"
