# Automatisierung für Luftbefeuchter EG
- alias: Luftbefeuchter Wohnzimmer on
  id: Luftbefeuchter Wohnzimmer on
  trigger:
    - platform: numeric_state
      entity_id: sensor.aranet4_02_kueche_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: humidifier.deerma_jsq2w_a365_humidifier
      state: 'off'  # Only trigger if the humidifier is currently off
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.luftbefeuchter_wohnzimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter EG
        message: "Luftbefeuchter EG an"
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_a365_humidifier
