- alias: Humidifier EG Empty Notification
  trigger:
    - platform: state
      entity_id: humidifier.deerma_jsq2w_a365_humidifier # Replace with your humidifier's entity ID
      attribute: custom.water_shortage_fault
      to: "true" # Trigger when the attribute becomes 'true'
  action:
    - service: notify.mobile_app_pixel_9_pro
      data:
        title: "Humidifier Alert EG!"
        message: "The humidifier in EG is empty. Please refill it."

- alias: Humidifier 1.OG Empty Notification
  trigger:
    - platform: state
      entity_id: humidifier.deerma_jsq2w_7134_humidifier # Replace with your humidifier's entity ID
      attribute: custom.water_shortage_fault
      to: "true" # Trigger when the attribute becomes 'true'
  action:
    - service: notify.mobile_app_pixel_9_pro
      data:
        title: "Humidifier Alert 1.OG!"
        message: "The humidifier in 1.OG is empty. Please refill it."

- alias: Humidifier 2.OG Empty Notification
  trigger:
    - platform: state
      entity_id: humidifier.deerma_jsq2w_b6e0_humidifier # Replace with your humidifier's entity ID
      attribute: custom.water_shortage_fault
      to: "true" # Trigger when the attribute becomes 'true'
  action:
    - service: notify.mobile_app_pixel_9_pro
      data:
        title: "Humidifier Alert 2.OG!"
        message: "The humidifier in 2.OG is empty. Please refill it."
