# Automatisierung für Luftbefeuchter 2.OG
- alias: Luftbefeuchter Arbeitszimmer on
  id: Luftbefeuchter Arbeitszimmer on
  trigger:
    - platform: numeric_state
      entity_id: sensor.aranet4_01_arbeitszimmer_humidity
      below: input_number.humidity_control_humidifier_start
      for: "00:01:00"
  condition:
    - condition: state
      entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
      state: "off" # Only trigger if the humidifier is currently off
  action:
    - service: input_boolean.turn_on
      target:
        entity_id: input_boolean.luftbefeuchter_arbeitszimmer_aktiv
    - service: logbook.log
      data:
        name: Luftbefeuchter 2OG
        message: "Luftbefeuchter 2OG an"
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
    - service: humidifier.turn_on
      target:
        entity_id: humidifier.deerma_jsq2w_b6e0_humidifier
