- platform: waste_collection_schedule
  name: waste_rest
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  # Filter auf den alias des Types
  types:
    - rest

# Since formating within Dashboards is so much fun (thanks Jinja for having the
# worst error messages on the planet), I add it here.
- platform: waste_collection_schedule
  name: waste_rest_display
  details_format: "upcoming"
  value_template: >
    {% if value.daysTo == "0" %}
      Heute
    {% elif value.daysTo == "1" %}
      Morgen
    {% else %}
      {{ value.daysTo}}
    {% endif %}
  # Filter auf den alias des Types
  types:
    - rest

- platform: waste_collection_schedule
  name: waste_gelb
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  # Filter auf den alias des Types
  types:
    - gelb

# Since formating within Dashboards is so much fun (thanks Jinja for having the
# worst error messages on the planet), I add it here.
- platform: waste_collection_schedule
  name: waste_gelb_display
  details_format: "upcoming"
  value_template: >
    {% if value.daysTo == "0" %}
      Heute
    {% elif value.daysTo == "1" %}
      Morgen
    {% else %}
      {{ value.daysTo}}
    {% endif %}
  # Filter auf den alias des Types
  types:
    - gelb

- platform: waste_collection_schedule
  name: waste_bio
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  # Filter auf den alias des Types
  types:
    - bio

# Since formating within Dashboards is so much fun (thanks Jinja for having the
# worst error messages on the planet), I add it here.
- platform: waste_collection_schedule
  name: waste_bio_display
  details_format: "upcoming"
  value_template: >
    {% if value.daysTo == "0" %}
      Heute
    {% elif value.daysTo == "1" %}
      Morgen
    {% else %}
      {{ value.daysTo}}
    {% endif %}
  # Filter auf den alias des Types
  types:
    - bio

- platform: waste_collection_schedule
  name: waste_papiertonne
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
  # Filter auf den alias des Types
  types:
    - papier

# Since formating within Dashboards is so much fun (thanks Jinja for having the
# worst error messages on the planet), I add it here.
- platform: waste_collection_schedule
  name: waste_papiertonne_display
  details_format: "upcoming"
  value_template: >
    {% if value.daysTo == "0" %}
      Heute
    {% elif value.daysTo == "1" %}
      Morgen
    {% else %}
      {{ value.daysTo}}
    {% endif %}
  # Filter auf den alias des Types
  types:
    - papier

- platform: waste_collection_schedule
  name: waste_next
  details_format: "upcoming"
  value_template: "{{ value.daysTo }}"
