# Stromkalkulation für Geräte ohne eigene Verbrauchsmessung
# https://www.simon42.com/home-assistant-powercalc/
# die entity_id ist die entity auf dessen Basis der Verbrauch berechnet wird
- platform: powercalc
  name: "Xiaomi Vacuum"
  entity_id: vacuum.roboter_staubsauger
  unique_id: "VacuumXiaomiSkippy"
  standby_power: 1
  fixed:
    states_power:
      cleaning: 33
      docked: 1
- platform: powercalc
  name: "Roborock Vacuum"
  entity_id: vacuum.roborock_s7_maxv
  unique_id: "VacuumRoboRock"
  standby_power: 3
  fixed:
    states_power:
      cleaning: 68
      docked: 3
- platform: powercalc
  name: "Helios Lüftung"
  entity_id: "sensor.helios_airflow_rate"
  standby_power: 0.5
  # https://www.farko.com/files/helios_kwl_katalog_6.0_0220_d.pdf
  linear:
    calibrate:
      - 0 -> 0.5
      - 140 -> 14
      - 200 -> 25
      - 350 -> 111
