sensor:
  - name: Grunbeck Gesamtwassermenge
    unique_id: grunbeck_gesamtwassermenge
    unit_of_measurement: "L"
    state_class: total_increasing
    device_class: water
    state: >-
      {% set wwh = states("sensor.grunbeck_weichwasser_harte")|float(0) %}
      {% set rwh = states("sensor.grunbeck_rohwasser_harte")|float(0) %}
      {% set wwm = states("sensor.grunbeck_weichwassermenge")|float(0) %}
      {% if (is_number(wwh) and (wwh > 1)) and (is_number(rwh) and (rwh > 1)) and (is_number(wwm) and (wwm > 1)) %}
        {% set gwn = ((wwh*wwm)/(rwh-wwh)+wwm)|round(4) |float(unavailable) %}
      {% endif %}
      {% if is_number(gwn) %}
        {{ gwn }}
      {% endif %}

  - name: watering_zone1_buffer_percent
    state: "{{ ((states('input_number.watering_zone1_threshold')|float - (states('input_number.watering_zone1_adjust')|float * states('sensor.zone1_smart_irrigation_daily_adjusted_run_time')|float)) / states('input_number.watering_zone1_threshold')|float) |round(4) * 100 }}"
    unit_of_measurement: "%"

  - name: watering_zone2_buffer_percent
    state: "{{ ((states('input_number.watering_zone2_threshold')|float - (states('input_number.watering_zone2_adjust')|float * states('sensor.zone2_smart_irrigation_daily_adjusted_run_time')|float)) / states('input_number.watering_zone2_threshold')|float) |round(4) * 100 }}"
    unit_of_measurement: "%"

  - name: watering_zone3_buffer_percent
    state: "{{ ((states('input_number.watering_zone3_threshold')|float - (states('input_number.watering_zone3_adjust')|float * states('sensor.zone3_smart_irrigation_daily_adjusted_run_time')|float)) / states('input_number.watering_zone3_threshold')|float) |round(4) * 100 }}"
    unit_of_measurement: "%"

  - name: watering_zone4_buffer_percent
    state: "{{ ((states('input_number.watering_zone4_threshold')|float - (states('input_number.watering_zone4_adjust')|float * states('sensor.zone4_smart_irrigation_daily_adjusted_run_time')|float)) / states('input_number.watering_zone4_threshold')|float) |round(4) * 100 }}"
    unit_of_measurement: "%"

  - name: watering_zone5_buffer_percent
    state: "{{ ((states('input_number.watering_zone5_threshold')|float - (states('input_number.watering_zone5_adjust')|float * states('sensor.zone5_smart_irrigation_daily_adjusted_run_time')|float)) / states('input_number.watering_zone5_threshold')|float) |round(4) * 100 }}"
    unit_of_measurement: "%"

  - name: watering_zone1_buffer
    state: " {{state_attr('sensor.zone1_smart_irrigation_daily_adjusted_run_time', 'bucket') }}"
    unit_of_measurement: "mm"

  - name: watering_zone2_buffer
    state: " {{state_attr('sensor.zone2_smart_irrigation_daily_adjusted_run_time', 'bucket') }}"
    unit_of_measurement: "mm"

  - name: watering_zone3_buffer
    state: " {{state_attr('sensor.zone3_smart_irrigation_daily_adjusted_run_time', 'bucket') }}"
    unit_of_measurement: "mm"

  - name: watering_zone4_buffer
    state: " {{state_attr('sensor.zone4_smart_irrigation_daily_adjusted_run_time', 'bucket') }}"
    unit_of_measurement: "mm"

  - name: watering_zone5_buffer
    state: " {{state_attr('sensor.zone5_smart_irrigation_daily_adjusted_run_time', 'bucket') }}"
    unit_of_measurement: "mm"

    # Veränderung der Wassermenge berechnet auf den nächsten Tag (Verdunstung - Niederschlag)
  - name: watering_general_netto_precipitation
    state: " {{ state_attr('sensor.zone1_smart_irrigation_hourly_adjusted_run_time', 'netto_precipitation') }}"
    unit_of_measurement: "mm"

    # Erwarteter Niederschlag
  - name: watering_general_precipitation
    state: " {{ state_attr('sensor.zone1_smart_irrigation_hourly_adjusted_run_time', 'precipitation') }}"
    unit_of_measurement: "mm"

    # Erwartete Verdunstung
  - name: watering_general_evapotranspiration
    state: " {{ state_attr('sensor.zone1_smart_irrigation_hourly_adjusted_run_time', 'evapotranspiration') }}"
    unit_of_measurement: "mm"

binary_sensor:
  # --------------------------------------------------------
  # Waste binary sensors
  #
  # Is a waste disposal close?
  # --------------------------------------------------------

  - name: template_waste_bio_upcoming
    state: >
      {{ states("input_boolean.template_show_all_conditionals") == "on" or states("sensor.waste_bio") |int < 2 }}

  - name: template_waste_rest_upcoming
    state: >
      {{ states("input_boolean.template_show_all_conditionals") == "on" or states("sensor.waste_rest_2") |int < 2 }}

  - name: template_waste_papiertonne_upcoming
    state: >
      {{ states("input_boolean.template_show_all_conditionals") == "on" or states("sensor.waste_papiertonne") |int < 2 }}

  - name: template_waste_gelb_upcoming
    state: >
      {{ states("input_boolean.template_show_all_conditionals") == "on" or states("sensor.waste_gelb") |int < 2 }}

  # --------------------------------------------------------
  # Plant moisture binary sensors
  # --------------------------------------------------------

  - name: template_plant_moisture_low
    state: >
      {% set result = namespace() %}  
      {% set result.res = false %}
      {% for state in states.plant if state.attributes.moisture_status == "Low" %}
        {% set result.res = true %}
      {% endfor %}  
      {{result.res or states("input_boolean.template_show_all_conditionals")}}

  - name: template_plant_bambus_moisture_low
    state: >
      {{ state_attr("plant.bambus", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on"}}

  - name: template_plant_elefantenfuss_moisture_low
    state: >
      {{ state_attr("plant.elefantenfuss", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on"}}

  - name: template_plant_flamingopflanze_moisture_low
    state: >
      {{ state_attr("plant.flamingopflanze", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on"}}

  - name: template_plant_geranie_moisture_low
    state: >
      {{ state_attr("plant.geranie", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on"}}

  - name: template_plant_glucksfeder_moisture_low
    state: >
      {{ state_attr("plant.glucksfeder", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on" }}

  - name: template_plant_strahlenaralie_moisture_low
    state: >
      {{ state_attr("plant.strahlenaralie", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on" }}

  - name: template_plant_alpenveilchen_moisture_low
    state: >
      {{ state_attr("plant.alpenveilchen", "moisture_status") == "Low" or states("input_boolean.template_show_all_conditionals") == "on" }}